### ISSUE TITLE
Missing bottom block in Minetest 5.4.1 (Fedora 35, Linux)

### ISSUE THREAD

**Issue by nik0380** [NO411/oneblock#1]
Hello!
Missing bottom block in Minetest 5.4.1 (Fedora 35, Linux). The character just falls into the void. When falling, new blocks are not generated. What could be the problem?

**Comment by NO411** [comment]
Which sub-game do you use?

**Comment by nik0380** [comment]
Hello!
I used  **Minetest Game**, **Development Test** and **MineClone2** with the same result.  Maybe I did something wrong. The package was installed from the repository. I tried also to install with Git, the result is the same, the program code is the same (lua). An optional dependency **mcl_cote** is missing, but I don't know where to get it. Many thanks for the prompt response.

**Comment by NO411** [comment]
I tested it again, 5.4.1 and 5.5 work for me with MTG and mcl2. Mineclone5 will probably not work due to mapgen changes in mcl5.
Make sure that you
- use singlenode mapgen
- activate mod

**Comment by NO411** [comment]
If you don't see the hud, you probably haven't activated the mod, so the block can't be generated.

**Comment by nik0380** [comment]
I did it! Thank you for help! Good game!
