### ISSUE TITLE
a second oneblock appeared

### ISSUE THREAD

**Issue by superfloh247** [NO411/oneblock#2]
Hi,

in my local oneblock world a second oneblock appeared which has no functionality (nothing spawning) and cannot be removed.

See coords in screenshot

![screenshot_20220721_152006](https://user-images.githubusercontent.com/26180993/180223909-b806af4f-d2a0-4100-83cb-561d0c94cca9.png)

Do you need anything else? world files, map, settings ... please just ask.

**Comment by NO411** [comment]
Weird, the block is supposed to spawn at 0, 0, 0. I can't imagine how that can happen.

**Comment by superfloh247** [comment]
At 0,0,0 there is a fully functional oneblock.

**Comment by NO411** [comment]
I know but i wonder what caused the second call of on_generated.

**Comment by superfloh247** [comment]
OK it did not suddenly appear, one of the kids placed it. The random generator created it.

**Comment by NO411** [comment]
Oh ok but that's still a problem IMO. You shouldn't be able to get the block, right?
I will fix that.

**Comment by superfloh247** [comment]
Any ideas how to get rid of the placed block?
I guess I'll have to learn WorldEdit now :)

**Comment by NO411** [comment]
Yeah just use world edit (or add ``groups = {cracky = 3},```to line 83 in the init.lua of the mod, break the block and then remove the line again.)
