### ISSUE TITLE
Playing on Android?

### ISSUE THREAD

**Issue by RolfWojtech** [NO411/oneblock#8]
Hey there, this looks like a pretty fun game mode, but I can't open it on minetest for Android since the singlenode mapgen isn't available there.

I found this thread that discusses that it is easily possible for mod creators to force the mapgen to singlenode:
https://github.com/minetest/minetest/issues/3844

Not sure if it that easy but it would be really cool if you could try this.

**Comment by NO411** [comment]
Fixed, thank you for the hint.
